env:
  global:
    secure: HJh15DR9Ugr1/51OrSGW2Yts3MlTh4RJ8/BvrhyP/VgOxkw1UdfeQVM0fe6roD2QbbPTE7xUk+CzBl3owgXEVkg3o7LQCuO45L3ay98zfsHoK9QK6kPNlkVnIeIo8aVO0HvxFXMCL41MsBXh0mjl1f8o1Te2Z3R9Kz346/d2LQaWA0R8dQPjjWLR5bsju1ozHCLQ/fLj1Qm/KNgZuPMtFGOnBMy1auuR6Ixf5kYDzv8+4gNjxfn0HPS88BeI6p6O5G7CKUxtEmB/Y+ht0uFxZPeazwFHlORlKy7kMfOfScykOKnIXm+SJUBbVtw9MEN/cB1KUV0T2CEk8gT+g8HcuqdAJUJfIULlXOgmZGv09v0yco+b6QL6C+Gl0lH6gjaHA7NkQUS4u3Y0tTHPsYs9NDSUD0fr+CNF5rdHuEUjtUUDoFtSuiQW8j0lvZEkhHewvPR3kLct1kQ6TypKTCPc+S6YlubtAUjexEGzn4J15/HwRYmY7KgkfrcgOCm8EH3dcO+IRHX2EOReH8boCdhmXL8Gd9bFGCRBAmzpJfcEiVyhSsBsL1vGxT0Av3aQH2SB1r0PnB1TQGuulR7ZXKZjrtCgcuD4Vb3k7XBMl5D0jmM3xmIFRpF+VuQLKf5Xx9jWuQYILItJd/0MvkYorezE12nuzWrbxBC4kkdakt12clA=
after_success:
  - $(npm bin)/set-up-ssh --key "${encrypted_f8ae8f7b3d49_key}"
      --iv "${encrypted_f8ae8f7b3d49_iv}"
      --path-encrypted-key .travis-github-deploy-key.enc
  - $(npm bin)/update-branch --commands 'npm run build && touch dest/.nojekyll'
      --commit-message "Update gh-pages @ ${TRAVIS_COMMIT}"
      --directory 'dest'
      --distribution-branch 'gh-pages'
      --source-branch 'master'
language: node_js
git:
  depth: 1
